### ISSUE TITLE
再Roll一次的时候不会去掉畅饮

### ISSUE THREAD

**Issue by 7gugu** [TransparentLC/saizeriya#1]
RT，原来设定是不要畅饮的，一次roll出来的结果也是对的，但是点击“再Roll一次”就会默认加上畅饮了

**Comment by TransparentLC** [comment]
我在考虑重写畅饮的抽取方式 _(:_」∠)_

打算是改成必定抽取/必定不会抽取/预算超过 30 时以 50% 概率抽取（现在的抽取方式）这三种选项，并且不受黑名单影响。

不过我也没能复现这个 bug，只要黑名单里写了 1888（畅饮的 ID）那就无论如何都不会出现畅饮。
